### ISSUE TITLE
Custom heads & 1.17

### ISSUE THREAD

**Issue by srnyx** [LuuckA21/HidePlayer#2]
Can I use custom player heads, if so, how?
Also, does the plugin fully work on 1.17.1? It seems to work, but just want confirmation.

**Comment by LuuckA21** [comment]
Do you use custom player heads as item to change visibility?
In 1.17.1 plugin works well.

**Comment by srnyx** [comment]
> Do you want to use custom player heads as item to change visibility?

Yeah, like the thing in `config.yml`


> In 1.17.1 plugin works well.

When I do `/hideplayer` it says that an internal error occurred, is that just cause the command doesn't exist?

**Comment by LuuckA21** [comment]
No you can not use player heads.
Tomorrow I will check command and add player heads
