### ISSUE TITLE
Triple toggled when right clicking while looking at block

### ISSUE THREAD

**Issue by srnyx** [LuuckA21/HidePlayer#3]
I think this only happens when the item is a peaceable block and the player is looking at another placed block:
![img](https://srnyx.is-from.space/r/ktorpd6bi9a.png)
*On to off, right-clicked once, doesn't happen when looking at nothing*

It still works, but just quite annoying for it to spam chat.

**Comment by LuuckA21** [comment]
Tomorrow I will release v1.3 with custom player heads and remove this bug
