### ISSUE TITLE
v1.3 changelog questions

### ISSUE THREAD

**Issue by srnyx** [LuuckA21/HidePlayer#6]
For reference:
![img](https://srnyx.has.rocks/r/ktzv8dftv9a.png)

1. It says "now you **cant**", was it supposed to say "now you **can**"?
2. How do I make it use a custom head?
3. What do you mean by "UPDATE THE CONFIG!!!"? Does that mean I have to save my config somewhere, delete the config on the server, let it regenerate, then copy/paste my settings back in?

**Comment by LuuckA21** [comment]
1. Sorry I mean CAN
2. you have to put CUSTOM_HEAD as material for show/hide item in config.yml
3. You have to update the config from v1.2 (delete config and new one will create in automatic)

**Comment by srnyx** [comment]
> 2. you have to put CUSTOM_HEAD as material for show/hide item in config.yml

Where would I put the Value/Texture ID?

**Comment by LuuckA21** [comment]
`# Item
item:
  enable: true
  slot: 6
  show:
    material: CUSTOM_HEADS
    name: "&7Players: &aVisible &7(Right-Click)"
    lore: "&7Right-Click to toggle player visibility!"
  hide:
    material: CUSTOM_HEADS
    name: "&7Players: &cHidden &7(Right-Click)"
    lore: "&7Right-Click to toggle player visibility!"`

CUSTOM_HEADS means give your head as item

**Comment by srnyx** [comment]
> material: CUSTOM_HEADS
> 
> CUSTOM_HEADS means give your head as item

So I can't use like a head from [Minecraft-Heads](https://minecraft-heads.com/custom-heads)?

**Comment by LuuckA21** [comment]
The only method to do in spigot API: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/meta/SkullMeta.html

**Comment by LuuckA21** [comment]
You can't use texture id or something like this. You have to use name of the player. I can add a section in config.yml where you can put name of the player's head do you want

**Comment by srnyx** [comment]
> You can't use texture id or something like this. You have to use name of the player. I can add a section in config.yml where you can put name of the player's head do you want

Would it be at all possible for you to also add a texture ID section or no?

**Comment by LuuckA21** [comment]
Yes I can add this, but texture ID need to be a player name of a officiali minecraft account

**Comment by srnyx** [comment]
> Yes I can add this, but texture ID need to be a player name of a officiali minecraft account

Why can't an actual texture ID from Minecraft Heads be used?

**Comment by LuuckA21** [comment]
The only method to take player head from Spigot API is to give a minecraft player

**Comment by srnyx** [comment]
> The only method to take player head from Spigot API is to give a minecraft player

Tons of other plugins allow texture IDs though

**Comment by LuuckA21** [comment]
Tomorrow I will check how to do

**Comment by LuuckA21** [comment]
Today I will release new version, you can use value from [https://minecraft-heads.com/custom-heads](url)
