### ISSUE TITLE
Custom heads not working

### ISSUE THREAD

**Issue by srnyx** [LuuckA21/HidePlayer#9]
They show Steves

**Comment by LuuckA21** [comment]
I test the plugin and works well. Send me the config.yml

**Comment by srnyx** [comment]
> I test the plugin and works well. Send me the config.yml

```yml
  show:
    material: PLAYER_HEAD
    name: "&a&lPlayers visible"
    lore: "&7Toggle player visibility"
    custom-head-value: "d0eb0ed869db9caf3d4ca44170d425f4630681e955db9dbc853e7acdc9e7e0a7" #Leave empty for player personal head
  hide:
    material: PLAYER_HEAD
    name: "&c&lPlayers hidden"
    lore: "&7Toggle player visibility"
    custom-head-value: "405d3db49124343754baf3b0830c6e94b587b1d93213298f732dd5012cd25a42" #Leave empty for player personal head```

**Comment by LuuckA21** [comment]
You have to use CUSTOM_HEAD no PLAYER_HEAD

**Comment by LuuckA21** [comment]
I will change CUSTOM_HEAD into PLAYER_HEAD, player head is more easy to use

**Comment by srnyx** [comment]
> I will change CUSTOM_HEAD into PLAYER_HEAD, player head is more easy to use

So should I keep it as `PLAYER_HEAD`?

**Comment by LuuckA21** [comment]
Yes in 5 minutes I will release new update to fix this
